"""Constants for AeroViewADSB."""

from homeassistant.const import (
    CONF_HOST,
    CONF_PORT,
    CONF_SCAN_INTERVAL,
    CONF_LATITUDE,
    CONF_LONGITUDE,
)

DOMAIN = "aero_view_adsb"

CONF_HOST = CONF_HOST
CONF_PORT = CONF_PORT

DEFAULT_HOST = "192.168.1.82"
DEFAULT_PORT = 8755
DEFAULT_SCAN_INTERVAL = 10

CONF_HOME_LATITUDE = CONF_LATITUDE
CONF_HOME_LONGITUDE = CONF_LONGITUDE